bumped emscripten from 3.1.43 -> 3.1.44
N.B. @mattkretz needed to add `<algorithm>` prior to including `<vir/simd.h>`  which seems to be missing for the internal `std::clamp(..)` usage by SIMD. Maybe something to add to SIMD directly. This made Emscripten/libc++ not compile

```cpp
[..]/vir-simd-src/vir/simd.h:2244:46: error: no member named 'clamp' in namespace 'std'; did you mean simply 'clamp'?
 2244 |     { return simd<T, A>([&](auto i) { return std::clamp(v[i], lo[i], hi[i]); }); }
      |                                              ^~~~~~~~~~
      |                                              clamp
[..]//vir-simd-src/vir/simd.h:2242:5: note: 'clamp' declared here
 2242 |     clamp(const simd<T, A>& v, const simd<T, A>& lo,
      |     ^
```

This is for simd's `GIT_TAG v0.2.0`.

beyond Emscripten >3.1.44...3.1.47 (at least) the following additional error occurs:

```cpp

[..]/graph-prototype/core/include/gnuradio-4.0/BlockTraits.hpp:382:103: error: no member named 'processBulk' in 'scale<int, 2>'
  382 |                                                         std::index_sequence<OutIdx...>) -> decltype(d.processBulk(std::get<InIdx>(inputs)..., std::get<OutIdx>(outputs)...)) {
      |                                                                                                     ~ ^
[..]/graph-prototype/core/include/gnuradio-4.0/BlockTraits.hpp:381:9: note: while substituting into a lambda expression here
  381 |         []<std::size_t... InIdx, std::size_t... OutIdx>(std::index_sequence<InIdx...>,
      |         ^
[..]/graph-prototype/core/include/gnuradio-4.0/BlockTraits.hpp:381:9: note: in instantiation of requirement here
  381 |         []<std::size_t... InIdx, std::size_t... OutIdx>(std::index_sequence<InIdx...>,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  382 |                                                         std::index_sequence<OutIdx...>) -> decltype(d.processBulk(std::get<InIdx>(inputs)..., std::get<OutIdx>(outputs)...)) {
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  383 |             return {};
      |             ~~~~~~~~~~
  384 |         }(std::make_index_sequence<traits::block::input_port_types<TDerived>::size>(), std::make_index_sequence<traits::block::output_port_types<TDerived>::size>())
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[..]/graph-prototype/core/include/gnuradio-4.0/BlockTraits.hpp:372:51: note: while substituting template arguments into constraint expression here
  372 | concept processBulk_requires_ith_output_as_span = requires(TDerived                                                                                                                       &d,
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  373 |                                                            typename meta::transform_types<detail::dummy_input_span, traits::block::input_port_types<TDerived>>::template apply<std::tuple> inputs,
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  374 |                                                            typename meta::transform_conditional<decltype([](auto j) { return j == I; }), detail::dynamic_span, detail::dummy_output_span,
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  375 |                                                                                                 traits::block::output_port_types<TDerived>>::template apply<std::tuple>
      |                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  376 |                                                                    outputs,
      |                                                                    ~~~~~~~~
  377 |                                                            typename meta::transform_conditional<decltype([](auto j) { return j == I; }), detail::nothing_you_ever_wanted, detail::dummy_output_span,
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  378 |                                                                                                 traits::block::output_port_types<TDerived>>::template apply<std::tuple>
      |                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  379 |                                                                    bad_outputs) {
      |                                                                    ~~~~~~~~~~~~~~
  380 |     {
      |     ~
  381 |         []<std::size_t... InIdx, std::size_t... OutIdx>(std::index_sequence<InIdx...>,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  382 |                                                         std::index_sequence<OutIdx...>) -> decltype(d.processBulk(std::get<InIdx>(inputs)..., std::get<OutIdx>(outputs)...)) {
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  383 |             return {};
      |             ~~~~~~~~~~
  384 |         }(std::make_index_sequence<traits::block::input_port_types<TDerived>::size>(), std::make_index_sequence<traits::block::output_port_types<TDerived>::size>())
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  385 |     } -> std::same_as<work::Status>;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  386 |     not requires {
      |     ~~~~~~~~~~~~~~
  387 |         []<std::size_t... InIdx, std::size_t... OutIdx>(std::index_sequence<InIdx...>,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[..]/graph-prototype/core/include/gnuradio-4.0/Block.hpp:652:81: note: while checking the satisfaction of concept 'processBulk_requires_ith_output_as_span<scale<int, 2>, 0UL>' requested here
  652 |                         if constexpr (traits::block::can_processOne<Derived> or traits::block::processBulk_requires_ith_output_as_span<Derived, i>) {
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Ralph J. Steinhagen <r.steinhagen@gsi.de>